"""update model table

Revision ID: 0b77af678c65
Revises: 51a1b8f14d58
Create Date: 2022-09-25 12:08:25.597499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b77af678c65'
down_revision = '51a1b8f14d58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('chat_id', sa.BIGINT(), nullable=False))
    op.create_unique_constraint(None, 'user', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'chat_id')
    # ### end Alembic commands ###
