"""update payment columns table

Revision ID: 229662d98271
Revises: 2ffe06b68567
Create Date: 2022-10-02 16:23:14.520344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229662d98271'
down_revision = '2ffe06b68567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('extra_charges', sa.Float(), nullable=False))
    op.add_column('payment_detail', sa.Column('is_monthly', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_detail', 'is_monthly')
    op.drop_column('payment', 'extra_charges')
    # ### end Alembic commands ###
