"""update payment table

Revision ID: 2ffe06b68567
Revises: ad0dc98d7e0d
Create Date: 2022-10-02 16:00:57.177722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ffe06b68567'
down_revision = 'ad0dc98d7e0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('discount', sa.Float(), nullable=False))
    op.add_column('payment', sa.Column('total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'total')
    op.drop_column('payment', 'discount')
    # ### end Alembic commands ###
