"""create initial tables

Revision ID: 4dcbdfa4c9f2
Revises: 
Create Date: 2022-09-25 00:26:30.097725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcbdfa4c9f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_type',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('home',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('location_name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_status',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_type',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_concept',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_status',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('home_service',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('home_id', sa.BIGINT(), nullable=True),
    sa.Column('service_id', sa.BIGINT(), nullable=True),
    sa.Column('description', sa.BIGINT(), nullable=False),
    sa.Column('capacity', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('home_id', sa.BIGINT(), nullable=True),
    sa.Column('product_id', sa.BIGINT(), nullable=True),
    sa.Column('status_id', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['inventory_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('rooms', sa.BIGINT(), nullable=False),
    sa.Column('capacity', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('home_id', sa.BIGINT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('last_name', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('home_id', sa.BIGINT(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_roomer', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('mac', sa.String(length=300), nullable=False),
    sa.Column('type_id', sa.BIGINT(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('home_id', sa.BIGINT(), nullable=True),
    sa.Column('service_id', sa.BIGINT(), nullable=True),
    sa.Column('type_id', sa.BIGINT(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['issue_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('payment',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status_id', sa.BIGINT(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('billed_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['payment_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_detail',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('payment_id', sa.BIGINT(), nullable=True),
    sa.Column('concept_id', sa.BIGINT(), nullable=True),
    sa.Column('service_id', sa.BIGINT(), nullable=True),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('inventory_id', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['payment_concept.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['home_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_detail')
    op.drop_table('room_user')
    op.drop_table('payment')
    op.drop_table('issue')
    op.drop_table('device')
    op.drop_table('user')
    op.drop_table('room')
    op.drop_table('inventory')
    op.drop_table('home_service')
    op.drop_table('service')
    op.drop_table('product')
    op.drop_table('payment_status')
    op.drop_table('payment_concept')
    op.drop_table('issue_type')
    op.drop_table('inventory_status')
    op.drop_table('home')
    op.drop_table('device_type')
    # ### end Alembic commands ###
