"""update tables

Revision ID: 51706dd78574
Revises: fa7452845d35
Create Date: 2022-09-25 14:49:20.272889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51706dd78574'
down_revision = 'fa7452845d35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('issue_ibfk_3', 'issue', type_='foreignkey')
    op.create_foreign_key(None, 'issue', 'service', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issue', type_='foreignkey')
    op.create_foreign_key('issue_ibfk_3', 'issue', 'home', ['service_id'], ['id'])
    # ### end Alembic commands ###
