"""update user table

Revision ID: 51a1b8f14d58
Revises: b5356efe9cb8
Create Date: 2022-09-25 09:33:05.558331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51a1b8f14d58'
down_revision = 'b5356efe9cb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=15), nullable=True))
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300),
               nullable=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
