"""update description service

Revision ID: 51fc1b9a0ee8
Revises: b68d201a18f8
Create Date: 2022-09-25 00:39:51.825778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51fc1b9a0ee8'
down_revision = 'b68d201a18f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_service', 'description',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=300),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_service', 'description',
               existing_type=sa.String(length=300),
               type_=mysql.BIGINT(display_width=20),
               nullable=False)
    # ### end Alembic commands ###
