"""update service home table

Revision ID: 75962913e3c8
Revises: d94a79e0b79f
Create Date: 2022-09-25 00:49:10.761209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75962913e3c8'
down_revision = 'd94a79e0b79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_service', 'home_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.alter_column('home_service', 'service_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('home_service', 'service_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.alter_column('home_service', 'home_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    # ### end Alembic commands ###
