"""update room

Revision ID: a09249881092
Revises: bc58228bf5e1
Create Date: 2022-09-27 22:06:37.627414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a09249881092'
down_revision = 'bc58228bf5e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_history',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('room', 'rooms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('rooms', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.drop_table('room_history')
    # ### end Alembic commands ###
