"""update room history table

Revision ID: ad0dc98d7e0d
Revises: a09249881092
Create Date: 2022-10-01 23:56:25.349276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0dc98d7e0d'
down_revision = 'a09249881092'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_history', sa.Column('is_first_month', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_history', 'is_first_month')
    # ### end Alembic commands ###
