"""update payment table

Revision ID: b0b6b5083bbd
Revises: 51706dd78574
Create Date: 2022-09-27 19:56:58.142122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b6b5083bbd'
down_revision = '51706dd78574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_monthly',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('concept_id', sa.BIGINT(), nullable=True),
    sa.Column('service_id', sa.BIGINT(), nullable=True),
    sa.Column('inventory_id', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['payment_concept.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['home_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_monthly')
    # ### end Alembic commands ###
