"""update home service

Revision ID: b68d201a18f8
Revises: 4dcbdfa4c9f2
Create Date: 2022-09-25 00:30:39.781143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68d201a18f8'
down_revision = '4dcbdfa4c9f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_service', sa.Column('is_billed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_service', 'is_billed')
    # ### end Alembic commands ###
