"""add payment deposit

Revision ID: b8560ebf514f
Revises: d122c9bb6030
Create Date: 2022-10-20 23:37:03.812160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8560ebf514f'
down_revision = 'd122c9bb6030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_deposit',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('payment_id', sa.BIGINT(), nullable=True),
    sa.Column('room_id', sa.BIGINT(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status_id', sa.BIGINT(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('billed_date', sa.DateTime(), nullable=True),
    sa.Column('refund_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['payment_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_deposit')
    # ### end Alembic commands ###
