"""update payments

Revision ID: bc58228bf5e1
Revises: 0fd18e7a7e11
Create Date: 2022-09-27 20:27:44.642928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc58228bf5e1'
down_revision = '0fd18e7a7e11'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_concept', sa.Column('service_id', sa.BIGINT(), nullable=True))
    op.add_column('payment_concept', sa.Column('inventory_id', sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, 'payment_concept', 'home_service', ['service_id'], ['id'])
    op.create_foreign_key(None, 'payment_concept', 'inventory', ['inventory_id'], ['id'])
    op.drop_constraint('payment_detail_ibfk_2', 'payment_detail', type_='foreignkey')
    op.drop_constraint('payment_detail_ibfk_5', 'payment_detail', type_='foreignkey')
    op.drop_column('payment_detail', 'inventory_id')
    op.drop_column('payment_detail', 'service_id')
    op.drop_constraint('payment_monthly_ibfk_4', 'payment_monthly', type_='foreignkey')
    op.drop_constraint('payment_monthly_ibfk_2', 'payment_monthly', type_='foreignkey')
    op.drop_column('payment_monthly', 'inventory_id')
    op.drop_column('payment_monthly', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_monthly', sa.Column('service_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('payment_monthly', sa.Column('inventory_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_monthly_ibfk_2', 'payment_monthly', 'inventory', ['inventory_id'], ['id'])
    op.create_foreign_key('payment_monthly_ibfk_4', 'payment_monthly', 'home_service', ['service_id'], ['id'])
    op.add_column('payment_detail', sa.Column('service_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('payment_detail', sa.Column('inventory_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.create_foreign_key('payment_detail_ibfk_5', 'payment_detail', 'home_service', ['service_id'], ['id'])
    op.create_foreign_key('payment_detail_ibfk_2', 'payment_detail', 'inventory', ['inventory_id'], ['id'])
    op.drop_constraint(None, 'payment_concept', type_='foreignkey')
    op.drop_constraint(None, 'payment_concept', type_='foreignkey')
    op.drop_column('payment_concept', 'inventory_id')
    op.drop_column('payment_concept', 'service_id')
    # ### end Alembic commands ###
