"""update payment table

Revision ID: d122c9bb6030
Revises: 229662d98271
Create Date: 2022-10-02 18:54:24.414920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd122c9bb6030'
down_revision = '229662d98271'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('pay_date', sa.DateTime(), nullable=True))
    op.drop_column('payment', 'payment_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('payment_date', mysql.DATETIME(), nullable=True))
    op.drop_column('payment', 'pay_date')
    # ### end Alembic commands ###
