"""update service table

Revision ID: d94a79e0b79f
Revises: 51fc1b9a0ee8
Create Date: 2022-09-25 00:46:45.568141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd94a79e0b79f'
down_revision = '51fc1b9a0ee8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_service', 'is_billed')
    op.drop_column('home_service', 'is_optional')
    op.add_column('service', sa.Column('is_billed', sa.Boolean(), nullable=True))
    op.add_column('service', sa.Column('is_optional', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'is_optional')
    op.drop_column('service', 'is_billed')
    op.add_column('home_service', sa.Column('is_optional', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('home_service', sa.Column('is_billed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
