"""create logging table

Revision ID: fe32496aebde
Revises: 0b77af678c65
Create Date: 2022-09-25 12:30:21.755307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe32496aebde'
down_revision = '0b77af678c65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logging',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('module', sa.String(length=300), nullable=False),
    sa.Column('action', sa.String(length=300), nullable=False),
    sa.Column('ref_user_id', sa.BIGINT(), nullable=True),
    sa.Column('type', sa.Enum('system', 'user', name='type'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action'),
    sa.UniqueConstraint('module')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logging')
    # ### end Alembic commands ###
